.TH "Calibrate.hpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calibrate.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalibrate\fP"
.br
.RI "\fILibrary for coordinates transformations\&. Calculates the equivalent coordinates between both coordinate systems equatorial and horizontal\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
