.TH "Calibrate.cpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calibrate.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Calibrate\&.hpp'\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QCompleter>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QException>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QRegExpValidator>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QCoreApplication>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
