.TH "OpenSkyPlanetarium.hpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenSkyPlanetarium.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StelModule\&.hpp'\fP
.br
\fC#include 'StelGui\&.hpp'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'StelPluginInterface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenSkyPlanetarium\fP"
.br
.RI "\fIThis is used to dynamically load Open Sky Planetarium plugin into stellarium\&. \fP"
.ti -1c
.RI "class \fBOpenSkyPlanetariumPluginInterface\fP"
.br
.RI "\fIThis class is used by Qt to manage a plug-in interface\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
