.TH "gui/OSPMainDialog (copy).cpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/OSPMainDialog (copy).cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OpenSkyPlanetarium\&.hpp'\fP
.br
\fC#include 'OSPMainDialog\&.hpp'\fP
.br
\fC#include 'ui_OSPMainDialog\&.h'\fP
.br
\fC#include 'Calibrate\&.hpp'\fP
.br
\fC#include 'StelApp\&.hpp'\fP
.br
\fC#include 'StelLocaleMgr\&.hpp'\fP
.br
\fC#include 'StelModule\&.hpp'\fP
.br
\fC#include 'StelModuleMgr\&.hpp'\fP
.br
\fC#include 'StelObjectMgr\&.hpp'\fP
.br
\fC#include 'StelUtils\&.hpp'\fP
.br
\fC#include 'StelFileMgr\&.hpp'\fP
.br
\fC#include 'StarMgr\&.hpp'\fP
.br
\fC#include 'StelAudioMgr\&.hpp'\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QCompleter>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QException>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QRegExpValidator>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QCoreApplication>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
