.TH "SerialCom.hpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerialCom.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include <QMutex>\fP
.br
\fC#include <QWaitCondition>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerialCom\fP"
.br
.RI "\fIThis class is used for funtions related to serial communication with the arduino\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
