.TH "LaserDev.hpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LaserDev.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtSerialPort/QSerialPortInfo>\fP
.br
\fC#include <QtSerialPort/QSerialPort>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QCoreApplication>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QThread>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include 'SerialCom\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLaserDev\fP"
.br
.RI "\fIThis class is used for funtions related to motion and turning the laser on and off\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
