.TH "OpenSkyPlanetarium.cpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenSkyPlanetarium.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StelApp\&.hpp'\fP
.br
\fC#include 'StelCore\&.hpp'\fP
.br
\fC#include 'StelLocaleMgr\&.hpp'\fP
.br
\fC#include 'StelModuleMgr\&.hpp'\fP
.br
\fC#include 'StelGui\&.hpp'\fP
.br
\fC#include 'StelGuiItems\&.hpp'\fP
.br
\fC#include 'OpenSkyPlanetarium\&.hpp'\fP
.br
\fC#include 'OSPMainDialog\&.hpp'\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <stdexcept>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
