.TH "gui/OSPMainDialog.hpp" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/OSPMainDialog.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Calibrate\&.hpp'\fP
.br
\fC#include 'StelDialog\&.hpp'\fP
.br
\fC#include 'LaserDev\&.hpp'\fP
.br
\fC#include 'StarMgr\&.hpp'\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QtSerialPort/QSerialPort>\fP
.br
\fC#include <QtSerialPort/QSerialPortInfo>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br
\fC#include <QAbstractSlider>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOSPMainDialog\fP"
.br
.RI "\fIThis is the main class used in connecting all the signals to gui\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
