.TH "SerialCom" 3 "Mon Jan 30 2017" "OpenSky Planetarium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerialCom \- 
.PP
This class is used for funtions related to serial communication with the arduino\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SerialCom\&.hpp>\fP
.PP
Inherits QThread\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBresponse\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBerror\fP (const QString &s)"
.br
.ti -1c
.RI "void \fBtimeout\fP (const QString &s)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialCom\fP (QObject *parent=0)"
.br
.ti -1c
.RI "\fB~SerialCom\fP ()"
.br
.ti -1c
.RI "void \fBsendRequest\fP (const QString &port, int waitTime, const QString &request)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used for funtions related to serial communication with the arduino\&. 
.PP
Definition at line 26 of file SerialCom\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QT_USE_NAMESPACE SerialCom::SerialCom (QObject *parent = \fC0\fP)"
Class constructor
.PP
Constructor: 
.PP
Definition at line 27 of file SerialCom\&.cpp\&.
.SS "SerialCom::~SerialCom ()"
Class destructor
.PP
Destructor: 
.PP
Definition at line 35 of file SerialCom\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SerialCom::error (const QString &s)\fC [signal]\fP"
Error from arduino 
.SS "void SerialCom::response (const QString &s)\fC [signal]\fP"
Response from the arduino 
.SS "void SerialCom::run ()"
To send a request to arduino and wait for response and to save it
.PP
\fBrun()\fP 
.PP
Definition at line 64 of file SerialCom\&.cpp\&.
.SS "void SerialCom::sendRequest (const QString &port, intwaitTime, const QString &request)"
To set the parameters that needed to sent to arduino 
.PP
\fBParameters:\fP
.RS 4
\fIport\fP name of the port on which request need to be sent 
.br
\fIwaitTime\fP wait time for the response from arduino 
.br
\fIrequest\fP a string to be sent to arduino
.RE
.PP
sendRequest(const QString, int, const QString): Send a request to arduino 
.PP
Definition at line 48 of file SerialCom\&.cpp\&.
.SS "void SerialCom::timeout (const QString &s)\fC [signal]\fP"
Timeout error from arduio 

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenSky Planetarium from the source code\&.
